erickzanardo/nes_ui

README.md

**READY**
Fixed Minor Typo in `Readme.md`

fix: minor Typo in `Readme.md`

---

CHANGELOG.md
README.md
example/lib/main.dart
example/lib/sections/sections.dart
example/lib/sections/selection_list.dart
lib/src/theme.dart
lib/src/widgets/nes_icon.dart
lib/src/widgets/nes_selection_list.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_selection_list_test.dart

feat: adding nes selection list

---

.github/workflows/main.yaml
example/pubspec.lock

feat: upgrade to flutter 3.7.0

---

CHANGELOG.md
README.md
example/lib/app/page/app_page.dart
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/custom_extensions.dart
example/lib/gallery/sections/sections.dart
lib/src/theme.dart

**READY**
Adding a way to provide a custom theme extension in the nes_ui theme.

feat(custom-extensions): add custom extensions in the theme

---

example/lib/advanced/rpg_menu/bloc/rpg_menu_cubit.dart
example/lib/advanced/rpg_menu/bloc/rpg_menu_state.dart
example/lib/advanced/rpg_menu/page/rpg_menu_page.dart
example/lib/gallery/sections/selection_list.dart
example/pubspec.lock
lib/src/widgets/nes_selection_list.dart
pubspec.yaml
test/src/widgets/nes_selection_list_test.dart

**READY**
Implement the basic foundation for handling focus on the selection list widget.

feat: handling focus on nest selection list

---

example/.gitignore
example/.metadata
example/lib/advanced/rpg_menu/page/rpg_menu_page.dart
example/lib/advanced/rpg_menu/rpg_menu.dart
example/lib/advanced/rpg_menu/widgets/char_row.dart
example/lib/advanced/rpg_menu/widgets/items_menu.dart
example/lib/advanced/rpg_menu/widgets/widgets.dart

**READY**
Add an inner screen to the rpg menu example so we can have a more complex flow and test the interaction better.
https://user-images.githubusercontent.com/835641/217026123-c51ac7e4-1da1-40af-aeb2-926c15d5e0b3.mov

feat: adding inner selection menu to the example

---

CHANGELOG.md
example/.gitignore
example/.metadata
example/lib/advanced/rpg_menu/widgets/items_menu.dart
example/pubspec.lock
lib/src/controller.dart
lib/src/nes_ui.dart
lib/src/widgets/nes_controller_focus.dart
lib/src/widgets/nes_selection_list.dart
lib/src/widgets/widgets.dart
pubspec.yaml
test/src/widgets/nes_selection_list_test.dart

feat: adding keyboard support

---

example/lib/advanced/rpg_menu/bloc/rpg_menu_cubit.dart
example/lib/advanced/rpg_menu/page/rpg_menu_page.dart
example/lib/advanced/rpg_menu/widgets/items_menu.dart
lib/src/widgets/nes_selection_list.dart
test/src/widgets/nes_selection_list_test.dart

**READY**
Add the cancel action to the `NesSelectionList`.

feat: adding cancel action to selection items

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/key_icons.dart
example/lib/gallery/sections/sections.dart
example/pubspec.lock
example/pubspec.yaml
lib/src/widgets/nes_icon.dart
lib/src/widgets/nes_key_icon.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_key_icon_test.dart

**READY**
https://user-images.githubusercontent.com/835641/219022548-1e168c73-d73e-45be-bfc2-711aa61544b3.mov

feat: adding nes key icon

---

CHANGELOG.md
example/lib/gallery/sections/containers.dart
lib/src/widgets/nes_container.dart

feat: add backgroundColor to NesContainer

---

.github/PULL_REQUEST_TEMPLATE.md

chore(pr-template): add "test" as a type of change

---

CHANGELOG.md
example/lib/gallery/sections/icons.dart
lib/src/widgets/nes_icon.dart

**READY**
Adds two new icons, for open and closed folder.

feat: adding folder icons

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/icon_buttons.dart
example/lib/gallery/sections/sections.dart
lib/src/widgets/nes_icon_button.dart
lib/src/widgets/nes_pressabled.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_icon_button_test.dart
test/src/widgets/nes_pressable_test.dart

**READY**
https://user-images.githubusercontent.com/835641/222419993-55bc52b9-fb7c-4976-ba42-41918e31b9e9.mov

feat: adding NesPressable and NesIconButton

---

CHANGELOG.md
README.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/icons.dart
example/lib/gallery/sections/iterable_options.dart
example/lib/gallery/sections/sections.dart
lib/src/widgets/nes_icon.dart
lib/src/widgets/nes_iterable_options.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_iterable_options_test.dart

**READY**
https://user-images.githubusercontent.com/835641/223487189-4e125c4e-84bb-4869-a021-b939bf62a846.mov

feat: adding nes iterable options

---

CHANGELOG.md
README.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/dialogs.dart
example/lib/gallery/sections/sections.dart
lib/src/widgets/nes_confirm_dialog.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_confirm_dialog_test.dart

**READY**
https://user-images.githubusercontent.com/835641/224578960-b3cad60e-9501-401c-b725-a51ec9061b4c.mov

feat: adding nes confirm dialog

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/screen_transitions.dart
example/lib/gallery/sections/sections.dart
lib/src/nes_ui.dart
lib/src/screen_transitions/nes_fill.dart
lib/src/screen_transitions/nes_horizontal_close.dart
lib/src/screen_transitions/nes_overlay_transition_widget.dart
lib/src/screen_transitions/nes_transition_widget.dart
lib/src/screen_transitions/nes_vertical_close.dart
lib/src/screen_transitions/screen_transitions.dart
lib/src/theme.dart
test/src/screen_transitions/nes_fill_test.dart
test/src/screen_transitions/nes_horizontal_close_test.dart
test/src/screen_transitions/nes_vertical_close_test.dart

**READY**
Adds some screen transitions.
https://user-images.githubusercontent.com/835641/226142347-2f0c2c0a-9780-4cb8-978d-e41a1e65893c.mp4

feat: adding screen transitions.

---

CHANGELOG.md
example/lib/gallery/sections/icons.dart
lib/src/widgets/nes_icon.dart

feat: adding three vertical dots icon

---

CHANGELOG.md
lib/src/widgets/nes_scrollbar.dart
lib/src/widgets/nes_single_child_scroll_view.dart
test/src/widgets/nes_single_child_scroll_view_test.dart

**READY**
This PR adds `NesSingleChildScrollview.clipContent` and also fix a minor bug in the `NesScollbar` which wasn't using the correct border color.

feat: NesSingleChildScrollview.clipContent

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/sections.dart
example/lib/gallery/sections/tab_view.dart
lib/src/widgets/nes_tab.dart
lib/src/widgets/nes_tab_view.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_tab_view_test.dart

**READY**
https://user-images.githubusercontent.com/835641/230799332-bd375ef6-99d5-44fd-aead-f51930f8e47a.mov

feat: adding tab view

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/icons.dart
example/lib/gallery/sections/sections.dart
example/lib/gallery/sections/split_panel.dart
example/pubspec.lock
lib/src/widgets/nes_icon.dart
lib/src/widgets/nes_split_panel.dart
lib/src/widgets/widgets.dart
pubspec.yaml
test/src/widgets/nes_split_panel_test.dart

**READY**
https://user-images.githubusercontent.com/835641/233363460-a8235c4e-f7bd-4153-a091-5d50041bbf0b.mov

feat: NesSplitPanel

---

lib/src/widgets/nes_split_panel.dart
test/src/widgets/nes_split_panel_test.dart

fix: nes split panel resize with initial values

---

.github/workflows/main.yaml
CHANGELOG.md
example/lib/gallery/sections/checkboxes.dart
example/lib/gallery/sections/icons.dart
example/lib/gallery/sections/text_fields.dart
lib/src/widgets/nes_check_box.dart
lib/src/widgets/nes_icon.dart
test/helpers/set_screen_size.dart

feat: Adding new and saveFile icons

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/sections.dart
example/lib/gallery/sections/snackbars.dart
lib/src/theme.dart
lib/src/widgets/nes_snackbar.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_snackbar_test.dart

**READY**
https://user-images.githubusercontent.com/835641/233515758-236ef403-b608-4a88-a17d-13c03577d4b3.mov

feat: adding snackbar

---

CHANGELOG.md
example/lib/gallery/sections/file_explorer.dart
lib/src/widgets/nes_file_explorer.dart
test/src/widgets/nes_file_explorer_test.dart

fix: file explorer was not updating on receiving new entries

---

CHANGELOG.md
example/lib/gallery/sections/icon_buttons.dart
lib/src/widgets/nes_icon_button.dart

**READY**
Add disabled state to the nes icon button

feat: disabled state to nes icon button

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/sections.dart
example/lib/gallery/sections/windows.dart
lib/src/widgets/nes_icon.dart
lib/src/widgets/nes_window.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_window_test.dart

feat: NesWindow

---

CHANGELOG.md
example/lib/gallery/sections/icons.dart
lib/src/widgets/nes_icon.dart

**READY**
Adding open and closed eye icons.

feat: adding eye icons

---

.github/workflows/gh-pages.yaml
.github/workflows/main.yaml
CHANGELOG.md
example/pubspec.lock
pubspec.yaml

feat: updating to last flutter stable (3.10)

---

CHANGELOG.md
example/lib/advanced/window_manager/page/window_manager_page.dart
example/lib/advanced/window_manager/window_manager.dart
example/lib/gallery/sections/icons.dart
example/lib/widgets/nes_scaffold.dart
lib/src/widgets/nes_icon.dart
lib/src/widgets/nes_window.dart
test/src/widgets/nes_window_test.dart

**READY**
https://github.com/erickzanardo/nes_ui/assets/835641/807ff365-bad4-4c32-a285-d6a35f0c8692

feat: adding resize/move/close handlers to windows

---

CHANGELOG.md
example/lib/gallery/sections/icons.dart
lib/src/widgets/nes_icon.dart

feat: adding download icon

---

CHANGELOG.md
lib/src/widgets/nes_window.dart

fix: macos fallback for nes windows

---

example/lib/gallery/sections/file_explorer.dart
lib/src/widgets/nes_file_explorer.dart

feat: adding xml, yaml and text file types to file explorer

---

CHANGELOG.md
lib/src/widgets/nes_tab_view.dart

**READY**
Tab children were losing state.

fix: tabview state

---

CHANGELOG.md
example/lib/gallery/sections/icons.dart
lib/src/widgets/nes_icon.dart

feat: adding exclamation and question mark block icons

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/sections.dart
example/lib/gallery/sections/tooltips.dart
lib/src/theme.dart
lib/src/widgets/nes_tooltip.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_tooltip_test.dart

**READY**
https://github.com/erickzanardo/nes_ui/assets/835641/657de230-5088-466d-a91d-17992d09f71b

feat: add tooltip widget

---

CHANGELOG.md
example/lib/gallery/sections/screen_transitions.dart
lib/src/screen_transitions/nes_horizontal_grid.dart
lib/src/screen_transitions/nes_vertical_grid.dart
lib/src/screen_transitions/screen_transitions.dart

**READY**
https://github.com/erickzanardo/nes_ui/assets/835641/24752aeb-4605-49ec-9c7d-a4eb17c4cbfa

feat: adding vertical and horizontal grid transition

---

CHANGELOG.md
example/lib/gallery/sections/tab_view.dart
lib/src/widgets/nes_tab.dart
lib/src/widgets/nes_tab_view.dart

feat: adding the option for tab views to be non closable

---

CHANGELOG.md
lib/src/theme.dart
lib/src/widgets/nes_button.dart

feat: adding border color to button theme

---

CHANGELOG.md
example/lib/gallery/sections/containers.dart
lib/src/theme.dart
lib/src/widgets/nes_container.dart

**READY**
`NesContainer` can have its `padding customizable now.

feat: Allow nes container to have customizable padding

---

CHANGELOG.md
example/lib/gallery/sections/dialogs.dart
lib/src/widgets/dialogs/dialogs.dart
lib/src/widgets/dialogs/nes_input_dialog.dart
test/src/widgets/dialogs/nes_input_dialog_test.dart

feat: adding NesInputDialog

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/icons.dart
example/lib/gallery/sections/loading_indicators.dart
example/lib/gallery/sections/sections.dart
lib/src/internal/internal.dart
lib/src/internal/ticker.dart
lib/src/widgets/nes_icon.dart
lib/src/widgets/nes_iterable_options.dart
lib/src/widgets/nes_loading_indicator.dart
lib/src/widgets/widgets.dart

https://github.com/erickzanardo/nes_ui/assets/835641/7585b1ff-df3a-47ac-97e7-04449ff0d91b

feat: Adding loading indicators

---

CHANGELOG.md
example/lib/gallery/sections/icons.dart
lib/src/widgets/nes_icon.dart

feat: bag/chest icon

---

CHANGELOG.md
lib/src/theme.dart
lib/src/widgets/nes_container.dart

feat: NesContainer can have its pixel size configurable

---

CHANGELOG.md
lib/src/theme.dart
lib/src/widgets/nes_button.dart

feat: nesbutton can have configurable pixel size in the theme

---

CHANGELOG.md
example/lib/gallery/sections/icon_buttons.dart
lib/src/widgets/nes_icon_button.dart
test/src/widgets/nes_icon_button_test.dart

chore: Updating changelog and minor improvement in the icon button logic

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/running_text.dart
example/lib/gallery/sections/sections.dart
lib/src/widgets/nes_running_text.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_running_text_test.dart

feat: adding running text

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/effects.dart
example/lib/gallery/sections/sections.dart
lib/src/widgets/nes_blinker.dart
lib/src/widgets/nes_selection_list.dart
lib/src/widgets/widgets.dart

feat: add nes blinker

---

CHANGELOG.md
lib/src/widgets/nes_running_text.dart
test/src/widgets/nes_running_text_test.dart

fix: NesRunningText would not update its text

---

CHANGELOG.md
lib/src/widgets/nes_pressabled.dart

feat: add behavior to NesPressable

---

README.md

feat: add discord link

---

CHANGELOG.md
example/lib/advanced/container_playground/container_playground.dart
example/lib/widgets/nes_scaffold.dart
lib/src/theme.dart
lib/src/widgets/containers/containers.dart
lib/src/widgets/containers/nes_container.dart
lib/src/widgets/containers/nes_container_corner_inner_square_painter.dart
lib/src/widgets/containers/nes_container_rounded_border_painter.dart
lib/src/widgets/containers/nes_container_square_corner_painter.dart
lib/src/widgets/widgets.dart

https://github.com/erickzanardo/nes_ui/assets/835641/b3f0106c-72dc-42ab-9e2a-b5b1c9878642

feat: Allowing containers to have its border customizable

---

CHANGELOG.md
lib/src/theme.dart

fix: theme lerp

---

CHANGELOG.md
lib/src/widgets/containers/nes_container.dart
widgetbook/lib/main.dart
widgetbook/lib/widgetbook/use_cases/containers.dart
widgetbook/lib/widgetbook/widgetbook.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart
widgetbook/lib/widgetbook/widgets/use_case_decorator.dart
widgetbook/test/widgetbook_test.dart

feat: NesContainer.paintBuilder to override the on on the theme

---

example/pubspec.lock
pubspec.yaml

feat: bumping mini sprite version

---

CHANGELOG.md
lib/src/screen_transitions/nes_overlay_transition_widget.dart
lib/src/theme.dart

feat: Allowing screen transitions to have their cursor customized

---

CHANGELOG.md
lib/src/widgets/nes_button.dart

feat: adding click cursor to NesButton

---

CHANGELOG.md
example/lib/gallery/sections/dialogs.dart
example/pubspec.lock
lib/src/controller.dart
lib/src/widgets/nes_controller_focus.dart

feat: Removing deprecations from flutter 3.18

---

CHANGELOG.md
example/lib/advanced/fixed_viewport/page/fixed_viewport_page.dart
example/lib/main_fixed_viewport_demo.dart
example/pubspec.lock
lib/src/widgets/dialogs/nes_dialog.dart
lib/src/widgets/nes_fixed_viewport.dart
test/src/widgets/nes_fixed_viewport_test.dart

fix!: NesDialogs are now aware of NesFixedViewport scaling

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/bottom_sheets.dart
example/lib/gallery/sections/sections.dart
lib/src/theme.dart
lib/src/widgets/nes_bottom_sheet.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_bottom_sheet_test.dart

https://github.com/erickzanardo/nes_ui/assets/835641/59cf3e10-244d-4ec5-8b43-e977d77838ba

feat: Adding NesBottomSheet

---

CHANGELOG.md
lib/src/widgets/dialogs/nes_dialog.dart

fix: Dialogs to not show material background color

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/section_header.dart
example/lib/gallery/sections/sections.dart
lib/src/widgets/nes_section_header.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_section_header_test.dart

feat: adding NesSectionHeader

---

CHANGELOG.md
lib/src/widgets/dialogs/nes_dialog.dart

feat: Close dialogs on esc

---

CHANGELOG.md
example/lib/gallery/sections/file_explorer.dart
example/pubspec.lock
example/pubspec.yaml
lib/src/widgets/nes_file_explorer.dart

feat: NesFileExplorer can have custom icons now

---

CHANGELOG.md
example/pubspec.lock
lib/src/theme.dart
lib/src/widgets/dialogs/nes_input_dialog.dart

feat: update to flutter 3.22.0

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/dropdown_menus.dart
example/lib/gallery/sections/sections.dart
example/pubspec.lock
lib/src/widgets/nes_dropdown_menu.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_dropdown_menu_test.dart
widgetbook/lib/widgetbook/use_cases/dropdown_menus.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart

**READY**
https://github.com/erickzanardo/nes_ui/assets/835641/cb30e334-55a8-495f-9c0e-8ed7a38d980f

feat: Dropdown widget

---

widgetbook/lib/widgetbook/use_cases/typography.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart

feat: adding widgetbook use cases for texts

---

CHANGELOG.md
example/pubspec.lock
lib/src/extensions/color.dart
lib/src/screen_transitions/nes_overlay_transition_widget.dart
lib/src/theme.dart
lib/src/widgets/nes_button.dart

feat: Adding a screen transition cursor to theme

---

CHANGELOG.md
example/lib/gallery/sections/icons.dart
lib/src/widgets/nes_icon.dart

feat: adding shovel icon

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/dpads.dart
example/lib/gallery/sections/sections.dart
lib/src/widgets/nes_dpad.dart
lib/src/widgets/widgets.dart
test/src/widgets/nes_dpad_test.dart
widgetbook/lib/widgetbook/use_cases/dpads.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart

feat: dpad

---

lib/src/widgets/nes_tab_view.dart

Add int initialTabIndex to NesTabView
Add override initState() to _NesTabViewState

feat: Add initialTabIndex to NesTabView

---

lib/src/widgets/nes_tooltip.dart

fixes #159 
Top  
Bottom  
**READY** (needs testing on web and mobile, also with other children besides NesButton)
* Has been tested as Windows application and with a NesButton as the child
Updated NesTooltip to use [OverlayPortal](https://api.flutter.dev/flutter/widgets/OverlayPortal-class.html).

fix: Update NesTooltip to use OverlayPortal

---

CHANGELOG.md
widgetbook/lib/widgetbook/use_cases/tooltips.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart

feat: adding tooltip widgetbook

---

widgetbook/lib/widgetbook/use_cases/checkered_decoration.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart

feat: adding NesCheckeredDecoration widgetbook use case

---

widgetbook/lib/widgetbook/use_cases/icons.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart

feat: Adding NesIcon widgetbook use case

---

widgetbook/lib/widgetbook/use_cases/blinker.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart

feat: adding blinker widgetbook

---

widgetbook/lib/widgetbook/use_cases/loading_indicator.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart

feat: Adding loading indicators widgetbook use case

---

widgetbook/lib/widgetbook/use_cases/icon_badge.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart

feat: Adding icon badge widgetbook use case

---

CHANGELOG.md
lib/src/widgets/dialogs/nes_dialog.dart
widgetbook/lib/widgetbook/use_cases/confirm_dialog.dart
widgetbook/lib/widgetbook/use_cases/input_dialog.dart
widgetbook/lib/widgetbook/use_cases/nes_dialog.dart
widgetbook/lib/widgetbook/widgetbook.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart

feat: Improving dialogs and adding use cases for it

---

lib/src/theme.dart

Some general comment updates in theme.dart
**READY**
updates to comments only

docs: Update comments in theme.dart

---

CHANGELOG.md
example/lib/gallery/gallery_page.dart
example/lib/gallery/sections/progress_bars.dart
example/lib/gallery/sections/sections.dart
lib/src/theme.dart
lib/src/widgets/nes_progress_bar.dart
lib/src/widgets/widgets.dart
widgetbook/lib/widgetbook/use_cases/progress_bar.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart

**READY** (needs testing on web and mobile)
* Has been tested as Windows application
Added NesProgressBar

feat: Add NesProgressBar

---

CHANGELOG.md
example/lib/gallery/sections/progress_bars.dart
lib/src/widgets/nes_progress_bar.dart
widgetbook/lib/widgetbook/use_cases/progress_bar.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart

fix: Alignment and sizing on the progress bar

---

CHANGELOG.md
lib/src/widgets/containers/containers.dart
lib/src/widgets/containers/nes_container_mini_sprite_painter.dart
widgetbook/lib/widgetbook/use_cases/containers.dart
widgetbook/lib/widgetbook/widgetbook.directories.g.dart
widgetbook/pubspec.yaml
widgetbook/test/widgetbook_test.dart

**READY**
Adding a painter to the nes container painters that allow the usages of mini sprite to drawn their borders.

feat: Adding mini sprite support to nes container painters

---

CHANGELOG.md
lib/src/theme.dart
lib/src/widgets/nes_button.dart

feat: Adding a customizable `CustomPainter` to `NesButton`.
